version: "3.3"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "3001:3000"
        volumes:
            - ./app/express-server:/app
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - "3002:3000"
        volumes:
            - ./app/react-app:/app
    database:
        image: mongo
        ports:
            - "3003:27017"

